import esbuild from 'esbuild';
import process from 'node:process';
import builtins from 'builtin-modules';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const prod = process.argv[2] === 'production';

/**
 * MathLive loads its KaTeX fonts at runtime from `MathfieldElement.fontsDirectory`,
 * which is a URL relative to the script. Inside Obsidian there is no such URL we can
 * rely on, so instead we take the escape hatch MathLive itself provides: if the CSS
 * custom property `--ML__static-fonts` is set, `loadFonts()` skips dynamic loading
 * entirely (see mathlive/src/core/fonts.ts).
 *
 * We therefore rewrite MathLive's own `mathlive-fonts.css`, replacing each
 * `url(fonts/X.woff2)` with a base64 `data:` URI, and concatenate our widget styles.
 * The result is the `styles.css` that Obsidian loads for us.
 */
function generateStyles() {
  const distDir = join(root, 'node_modules', 'mathlive');
  const fontsCssPath = join(distDir, 'mathlive-fonts.css');
  if (!existsSync(fontsCssPath))
    throw new Error(`Cannot find ${fontsCssPath} — run \`npm install\` first.`);

  const fontsCss = readFileSync(fontsCssPath, 'utf8');

  const inlined = fontsCss.replace(/url\(fonts\/([^)]+\.woff2)\)/g, (_, file) => {
    const buf = readFileSync(join(distDir, 'fonts', file));
    return `url(data:font/woff2;base64,${buf.toString('base64')})`;
  });

  if (inlined.includes('url(fonts/'))
    throw new Error('Some font URLs were not inlined.');
  if (!inlined.includes('--ML__static-fonts'))
    throw new Error('mathlive-fonts.css no longer sets --ML__static-fonts.');

  const own = readFileSync(join(root, 'src', 'styles.src.css'), 'utf8');

  writeFileSync(
    join(root, 'styles.css'),
    `/* GENERATED by esbuild.config.mjs — do not edit. Edit src/styles.src.css. */\n` +
      `${inlined}\n\n${own}`,
  );
}

generateStyles();

/**
 * At import time MathLive computes the URL it was served from, so it can resolve
 * `fontsDirectory` and `soundsDirectory` against it. It reads
 * `document.currentScript.src`, and when that is null it falls back to parsing
 * `new Error().stack` for its own location. Obsidian evaluates `main.js` with no script
 * element, so both fail and MathLive logs two `console.error`s on every plugin load.
 *
 * We never resolve a relative asset URL — `main.ts` sets both directories to null, and
 * the fonts are inlined into `styles.css` above — so pin the base URL to the app's own
 * and drop the stack-trace probe. Throws on a MathLive upgrade that changes this shape,
 * rather than silently leaving the probe in.
 */
const pinMathLiveScriptUrl = {
  name: 'pin-mathlive-script-url',
  setup(build) {
    build.onLoad({ filter: /mathlive[\\/]mathlive(\.min)?\.mjs$/ }, (args) => {
      const src = readFileSync(args.path, 'utf8');
      const probe = /(\w+)\s*=\s*\(\([^;]*?currentScript[^;]*?\.src\)\s*\|\|\s*\w+\(\)/;
      if (!probe.test(src))
        throw new Error(
          `${args.path}: no currentScript fallback found — has MathLive changed how it ` +
            `resolves its script URL? Re-check that the load-time console errors are gone.`,
        );
      return {
        contents: src.replace(probe, '$1 = globalThis.location?.href ?? ""'),
        loader: 'js',
      };
    });
  },
};

const context = await esbuild.context({
  entryPoints: ['src/main.ts'],
  bundle: true,
  plugins: [pinMathLiveScriptUrl],
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: 'main.js',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
